### ISSUE TITLE
[BUG] - Running the contributed command: 'numberedBookmarks.toggleBookmark1' failed.

### ISSUE THREAD

**Issue by pochka15** [alefragnani/vscode-numbered-bookmarks#100]
## Here is the [video](https://www.dropbox.com/s/vzhsvnrkfh6ez2i/2021-02-26%2011-58-11.mkv?dl=0)

![image](https://user-images.githubusercontent.com/24525928/109279119-6c8be880-782a-11eb-9823-016d39e19d0a.png)

**Windows**

- Extension version: 8.02 (default settings)
- VSCode version: 1.53.2 (user setup)

**Steps to reproduce**

1. Create any file with any extension
2. Set the bookmark

**Notes**

When I set the bookmark vscode shows this error and the gutter is not rendered. But I can jump to the created bookmark. What's interesting is that when I hit save (ctrl + s) then It gets rendered sometimes.

**Comment by pochka15** [comment]
I don't know... Looks like now everything works correctly. But what was the problem?

**Comment by JeroenBos** [comment]
I have the same on 2 machines, since a few weeks (I don't think it's coincidence that the latest version 8.0.0 was released 19 days ago). Reinstallation of the extension version 8.0.0 did not fix it. 

Downgrading to 7.3.0 did work. So it appears 8.0.0 is just completely broken as far as I can tell. 


------
P.S. As for what is the latest version, I'm not sure how this project works exactly, but vscode lists 8.0.0 as latest, GitHub releases lists 8.0.1 as latest, and OP seems to have 8.0.2.

**Comment by chipbite** [comment]
I am experiencing this issue as well. Started a few versions ago, @JeroenBos might have it right.
It works a bit, then stops and you get the toggle failed notification box...
![image](https://user-images.githubusercontent.com/559199/110528997-0439e280-8119-11eb-840a-b3d01b0c1a67.png)

**Comment by alefragnani** [comment]
I've detected two issues with the new release. 

* One is relative to `Untitled` files, which are those that you create using the `New File` command. Based on your descriptions, this is probably what is happening, and #99 was already created to track it. 
* The other is relative to `deleted files`, but you will only notice when you try to _navigate_ between bookmarks. This will be fixed in #102.

Sorry about the mess. I'm planning to release a fix until the weekend.

Hope this helps
