### ISSUE TITLE
[BUG] - Breakpoint can't be disabled when bookmark is present

### ISSUE THREAD

**Issue by rickstaa** [alefragnani/vscode-numbered-bookmarks#122]
Not a big bug but it seems that breakpoints can not be disabled when they are under a bookmark.

![breakpoint_problem](https://user-images.githubusercontent.com/17570430/142215116-91e929d8-bef9-4771-982e-cdc590663213.gif)

**Environment/version**

- Extension version: v8.1.0
- VSCode version: 1.62.2
- OS version: Ubuntu 20.04

**Steps to reproduce**

1. Open vscode.
2. Create file.
3. Set breakpoint.
4. Add bookmark on same line.

**Comment by alefragnani** [comment]
Hi @rickstaa ,

This is a known issue, caused by VS Code. It was first reported in 2016 (https://github.com/microsoft/vscode/issues/5923), but up until today, it wasn’t fixed. 

Unfortunately, there is nothing I can do, as it is totally controlled by VSCode.

When they finally fix this, I guess we (extension developers) won’t need to do anything on our side.

Hope this helps
