### ISSUE TITLE
[BUG] - Cannot toggle breakpoint if line has a bookmark

### ISSUE THREAD

**Issue by ejkitchen** [alefragnani/vscode-numbered-bookmarks#126]
- Extension version: v8.1.0
- VSCode version: 1.63.2
- OS version: Mac OS 12.01

**Steps to reproduce**

1. Set a breakpoint on a line (in my case Python file)
2. Set a bookmark for that line
3. Try to toggle breakpoint to turn it off (you cannot)

The reverse is also true. If you have a bookmark defined, you cannot enable breakpoints

**Comment by alefragnani** [comment]
Hi @ejkitchen ,

This is a known issue, caused by VS Code. It was first reported in 2016 (microsoft/vscode#5923), but up until today, it wasn’t fixed.

Unfortunately, there is nothing I can do, as it is totally controlled by VS Code.

When they finally fix this, I guess we (extension developers) won’t need to do anything on our side.

Hope this helps
