### ISSUE TITLE
[BUG] - Jump To Bookmark opens File instead of Refocusing When In Separate WindowGroups

### ISSUE THREAD

**Issue by kschatzle** [alefragnani/vscode-numbered-bookmarks#136]
**Environment/version**

- Extension version: 8.2
- VSCode version: 1.67.0 (Universal)
- OS version: MacOs 11.6

**Steps to reproduce**

1. Open Two Groups
2. File A is in first Group 
3. File B is in second Group
4. Toggle Bookmark in File A
5. Go to File B (which is in second group)
6. Jump To Bookmark
7. File A is opened in Group 2 as opposed to Jumping to File A in Group 1

**Comment by stephenlevitt** [comment]
The keyboard shortcuts for focusing editor groups (`ctrl-1`, `ctrl-2`, etc) conflict with the Jump to Bookmark shortcuts. I'm not sure if this related. (It definitely makes this extension hard to use because of keyboard re-mapping that is required.)

**Comment by alefragnani** [comment]
Hi @kschatzle,

Unfortunately, there is no way to fix is today, because there is no API to detect if some file is already open in some other editor group. So, the extension can only asks to open a file, and VS Code will take care of it. In this case, using the same editor group you already are.

@stephenlevitt , thanks for pointing out but, there is no connection between this issue and the shortcut conflict. In fact, is VS Code which is conflicting with my extension, not the opposite. My extension exists for 6 years, and there was no conflict with it back then. I guess these shortcuts where added recently, just like a few others I noticed, not only in VS Code itself, but on some other MS extensions, like Live Share.

Hope this helps

**Comment by stephenlevitt** [comment]
@alefragnani Thanks for replying. Perhaps it is worth offering users an option to use different, non-conflicting shortcuts. I'm not sure what shortcuts would make sense though.

**Comment by alefragnani** [comment]
The extension can only offer one shortcut per command. VS Code doesn't provide an API to deal with the possibility of conflicts. 

So, it is up to the user to manage the conflict when it happens, and he/she must choose a different shortcut to one of the conflicting extensions, using the [keyboard shortcuts editor](https://code.visualstudio.com/docs/getstarted/keybindings)

**Comment by alefragnani** [comment]
I’m closing this issue because VS Code doesn’t provide a proper API. So, this can’t be fixed

Thanks for your understanding.

**Comment by lstkz** [comment]
@alefragnani 
I did some quick research, and I think it's possible to implement.
For me, it's also a very important feature.

When opening the document, you can specify `viewColumn`.

```ts
// tab and group is hardcoded
// need to find the target file by looking and the uri
const tabGroup = vscode.window.tabGroups.all[0];
const tab = tabGroup.tabs[0];
vscode.window.showTextDocument((tab.input as vscode.TabInputText).uri, {
  viewColumn: tabGroup.viewColumn,
});
```
