### ISSUE TITLE
[FEATURE] - Allow multiple bookmarks on same line

### ISSUE THREAD

**Issue by petkaantonov** [alefragnani/vscode-numbered-bookmarks#158]
There can be multiple positions on same line to be bookmarked. It won't play well with the UI design so it should be configurable and not the default I guess.

Workaround before implemented (specific to 8.3.1):

```
const {readFileSync, writeFileSync} = require("fs")
const file = "/Users/petka2/.vscode/extensions/alefragnani.numbered-bookmarks-8.3.1/dist/extension-node.js"
const contents = readFileSync(file, "utf-8").replace('const s=(0,i.indexOfBookmark)(f,n.line)', 'const s=-1')
writeFileSync(file, contents, "utf-8")
```

If you are curious, why I need it. I implemented my own cursor undo because built in undo is useless. I want to jump around edit some things quickly and then jump back to where I was, but the built-in undo is reset any time you edit anything (there is no sticky engine). I keep undo and redo stacks as hidden bookmarks using this extension because of the sticky engine, so I don't need any of the ui features for this use case.

**Comment by alefragnani** [comment]
Hi @petkaantonov ,

Multiple bookmarks on the same line would break no only the UI, but some compatibilities that I'm planning for the future so, it's not that simple to accomplish and keep the extension with its original intention working properly.

Based on the description of your use case, it seems that what you really need is something like a Stack Bookmark, no matter the _numbers_ in it. If that's the case, I wonder if those Vim extensions has something like this natively, but I think it worth a try. Or, it would be easier (less breaking changes) to achieve this on my other Bookmarks extension, since there would be no _override_ of numbers per line (open issue https://github.com/alefragnani/vscode-bookmarks/issues/183).

Hope this helps.
