### ISSUE TITLE
[QUESTION] - Why is 8.5.0 not published

### ISSUE THREAD

**Issue by Bjorn-Eric-Abr** [alefragnani/vscode-numbered-bookmarks#177]
Hello!

Thanks for a great plugin.
Why is 8.5.0 not published to VSCode Marketplace? I can see that the build is failing, related?

**Comment by alefragnani** [comment]
Hi @Bjorn-Eric-Abr ,

No real reason, other than I forgot to publish it 🤦 

It was probably because I was publishing all my extensions to open-vsx for the first time, and this one was missing in the (still manual) process.

Anyway, I just published, so you can get it right in the marketplace.

Thanks for reporting

**Comment by Bjorn-Eric-Abr** [comment]
Nice! Really looking forward to the scroll position feature, thank you!
