### ISSUE TITLE
Avoid unnecessary scrolling

### ISSUE THREAD

**Issue by hugbug** [alefragnani/vscode-numbered-bookmarks#18]
I suggest a small change to make it more Delphi like. Currently when jumping to a bookmark the editor always centers the bookmark line. The centering however should not happen if the bookmark line was already visible on the screen.

To achieve this change `InCenter` to `InCenterIfOutsideViewport` in 
https://github.com/alefragnani/vscode-numbered-bookmarks/blob/master/extension.ts#L544:
```javascript
vscode.window.activeTextEditor.revealRange(newSe, vscode.TextEditorRevealType.InCenter);
```

**Comment by alefragnani** [comment]
Hi @hugbug ,

I forgot to add a small feature that I used in my other [Bookmarks](https://github.com/alefragnani/vscode-bookmarks) extension, that avoids centering if you already is positioned at the bookmark. That avoids the scrolling in one situation.

Even so, since the extension's main idea is to have a _Delphi like_ bookmarks experience, it should avoid the scrolling _when possible_ 👍 . 

Stay tuned for an update 😄
