### ISSUE TITLE
Bookmark disapear

### ISSUE THREAD

**Issue by zabel-xyz** [alefragnani/vscode-numbered-bookmarks#23]
First of all, thank you for this extension. It works as in Delphi where I usually use bookmarks ...

But now, I have some issues:
- Delete a line (editor.action.deleteLines) => Delete the associated bookmark (does not work as in Delphi)
![bookmark-deleteline](https://cloud.githubusercontent.com/assets/16486407/25312526/f550e2fa-281b-11e7-8d52-0babbe269f37.gif)

- Add empty line => Bookmarks below move or disapear
![bookmark-addemptyline](https://cloud.githubusercontent.com/assets/16486407/25312618/4a8acdce-281e-11e7-8004-56abb0ac1205.gif)

![bookmark-addemptylinemove](https://cloud.githubusercontent.com/assets/16486407/25312654/3894acce-281f-11e7-9f2d-136958c65773.gif)

**Comment by alefragnani** [comment]
Hi @zabel-xyz , I'm glad you liked it :)

About the _below move or disappear_ issue, I think it may be caused by the same issue that happened on my other bookmarks extension. Unfortunately, when I was _replicating the code_ here, I couldn't reproduce the issue, so I didn't update the code. I will give another try and see if it fixes.

About the _delete_ issue, I would say that I prefer _my way_ over the _original Delphi_ 😄 . Basically because the intention of the `sticky` bookmark is that it should be glued to the line of code, and since the line has been deleted, the bookmark must be deleted too. 

Thanks for reporting.

**Comment by ephemere000** [comment]
> About the delete issue, I would say that I prefer my way over the original Delphi 😄 . Basically because the intention of the sticky bookmark is that it should be glued to the line of code, and since the line has been deleted, the bookmark must be deleted too.

Respectfully, I totally disagree with this statement.

First, let me tell you how pleased I was that someone created a bookmark extension for VSC. I could not live without this, it is part of any professional IDE. I installed yours and it was as easy to toggle and go to bookmarks as in Visual Studio (not Code), contrarily to bad implementations like PHPStorm.

The sad thing is, and it is probably easy to fix, my bookmarks kept disappearing, some would not even last 2 mins, which defies the whole point of having bookmarks in the first place. I lost a few hours, re-sticking them over and over, lost patience and uninstalled the whole thing. It was driving me crazy and I lost too much productivity, again, defying the purpose of bookmarks. 

Using your bookmarks, each time I inserted code in my first bookmark above, the second one would disappear below. Each time I inserted code in the area of the second bookmark, I would zap it! It infuriated me. I ended up using global search and _Go to line_ as a compromise.

Two major problems: They disappear when we add code above and they disappear if we delete the line where they are stuck. 

First, a bookmark is useful to mark an **approximate** region of the code. Yes, we do mark a specific line but we rarely intend to go back to that line **specifically** each time.  We typically put it in the area we are doing some modifications. Bookmarks are not used as links to go back and forth between **static**  pages to a very specific line in a read only style mode. They are meant to locate quickly an approximate region where we are **intensively** revisiting and modifying code, to switch quickly between context. 

You are guarantied to quickly add, delete lines above, below and on the bookmark itself. Typically the line containing the bookmark will change very quickly because of a snippet insertion, reformatting, cut and paste... **We do want though** to go to the **closet** nearby location. In professional software like Visual Studio (not Code), the bookmarks often shift lines a bit as we modify intensely the code. It's OK, we just reposition them a bit above or below when required.  At least, we don't have to redo a global search each time trying to locate that region again from keywords that are not always so specific. Search, F3, F3, F3. F3. Yep that is where are my modifications... That is why bookmarks were invented, to locate an area, not a line. If not, just use the _Go to line_ feature, it does exactly this.

I love having bookmarks and I can't thank you enough to graciously spend time developing this extension for VSC. Unfortunately, I won't be able to use it in its current state. I suggest you look at other implementations and serious IDEs. They often have reasons why they are doing things in a certain way after many years of development and feedback.

Thank you again.
