### ISSUE TITLE
Feature request: config option for not delete bookmark if associated line is deleted

### ISSUE THREAD

**Issue by kkozlik** [alefragnani/vscode-numbered-bookmarks#27]
I am writing this feature request as a reaction on now closed issue #23. I 100% agree with @ephemere000 argumentation. My bookmarks are disappearing from time to time and for long time I did not know the reason. Until I have noticed that bookmark disappear because of I delete the associated line. 

But I respect your opinion as you say that your way is better. Just please add an config option for changing the behavior for those whom this behavior does not fit.

Thank you for this great extension!

**Comment by ibraimgm** [comment]
@kkozlik , I guess PR #43 does the trick for your scenario.

**Comment by kkozlik** [comment]
Yes it seems it does. Thank you!

**Comment by Daijobou** [comment]
I would love this feature!

**Comment by heinrich-ulbricht** [comment]
Chiming in from 2021 - I finally also discovered why my bookmarks keep disappearing. I delete code lines that contained them! Cannot remember this happening in the Delphi times 🤔 And this seems to happen so often that I thought the extension was broken. +1 from me

**Comment by alefragnani** [comment]
Hi @heinrich-ulbricht ,

Right now I have only Atom and IntelliJ installed, and both works exactly the same. When you delete a line with a bookmark or a breakpoint (in IntelliJ), the bookmark/breakpoint is deleted as well. These apps weren't the reasons why I made this way, but are examples of similar approach.

On the other hand, VS Code breakpoints works the way you described. When you delete the line, the breakpoint moves to the next line. Doing a quick test I already found an issue on this behavior. If you Undo the line deletion, the breakpoint doesn't undo as well, remaining in the next line. I imagine why they (the VS Code team) decided this approach, and TBH, the extension should follow the same approach.

I closed the PR that was linked to this issue, not only because it still had a few issues, but also because that piece of source code is now closed-source. I will revisit this request and I hope to have something for upcoming releases.

Stay tuned.

**Comment by alefragnani** [comment]
I wonder, what is the expected behavior when you delete _some lines with bookmarks_ and below the selected lines, you have another bookmark defined. I mean, you can only have one bookmark per line so....

Just tested how breakpoint works on VS Code and boom, the breakpoint is deleted. Just like bookmarks, you can only have one breakpoint per line.

Well, _follow the pattern_ 😬

**Comment by alefragnani** [comment]
## New Sticky Behavior for `Line Delete`

A new **Sticky** behavior has been added, and will be available as an _opt-in_ setting in the upcoming releases.

### Objective

When you delete a line that contains a bookmark, the bookmark will not be deleted anymore. Instead, it will be moved to the next line.

### Scenarios

1. You delete a line with a bookmark. The Bookmark is moved to the next line
2. You delete a bunch of lines, with a bookmark in some of them. The Bookmark is moved to the next line after the selected/deleted lines
3. You delete a bunch of lines, with a bunch of bookmarks in some of them. Only the bookmark located higher is moved to the next line after the selected/deleted lines. The rest of the bookmarks is really deleted.

> **Important (on any scenario)**: If the _next line_ already contains a bookmark, no bookmark will be moved. It means that those bookmarks in the deleted lines will be deleted as well. 

### How to Use (opt-in)

You should set `numberedBookmarks.keepBookmarksOnLineDelete` setting to `true`, in order to choose this behavior.

### `Undo` operations

It **does not support** `Undo` operations. 

I means that, once you delete a line and the bookmark is moved to the _next available line_, the `Undo` operation won't move the bookmark back to the previous line. The _next line_ is now the new location of the Bookmark.

This is exactly the same behavior as Breakpoints works in VS Code, and no undo support is planned.
