### ISSUE TITLE
Bookmark doesn't work across multiple files

### ISSUE THREAD

**Issue by Eisenspalter** [alefragnani/vscode-numbered-bookmarks#3]
Bookmark doesn't work across multiple files.

**Comment by alefragnani** [comment]
Hi,

That is the expected behavior. Each file can have up to 9 bookmarks, and using the `Jump to Bookmark #` command will look only on the active file.

I pretend to add a new command that will show/navigate _all bookmarks from all file_, similar to [issue #8 in Bookmarks extension](https://github.com/alefragnani/vscode-bookmarks/issues/8), but the keybindings (`Jump to Bookmark #`) will remains in the active file.

Hope this helps.

**Comment by alefragnani** [comment]
Hi @Eisenspalter,
Just released version 0.5.0 with this feature. Give it a try 😄

**Comment by Eisenspalter** [comment]
Great I will use it
