### ISSUE TITLE
Define background for bookmarked lines

### ISSUE THREAD

**Issue by Rah1x** [alefragnani/vscode-numbered-bookmarks#33]
is there a way to set a tint background of the bookmarked lines? Thats really helpful.
Thanks

**Comment by alefragnani** [comment]
Hi @Rah1x ,

Currently, there is no way to define a background color for bookmarked lines. It only adds an icon in the gutter.

But this is something that could be added in the future 👍 

Thanks for your suggestion.

**Comment by ibraimgm** [comment]
@Rah1x and @alefragnani , I did a shot at this on PR #44. Two new options were created, one to enable/disable this feature (`decorateWholeLine`, default `false`) and one to customize the color (`lineDecoratorColor`).

**There is a little catch:** since the bookmark styles are created and cached when the plugin activates, you have to restart for the changes to take effect... I don't know exactly how to detect a configuration change to rebuild the cache...

**Comment by alefragnani** [comment]
Hi @ibraimgm ,

I just merged you PR to master, and added the auto-detection of settings changes. So, it won't be necessary to reload/restart to the changes take effect.

A new release in on the way. Stay tuned.
