### ISSUE TITLE
Using short-cuts on Mac

### ISSUE THREAD

**Issue by itsthomas** [alefragnani/vscode-numbered-bookmarks#40]
Hi,
On a Mac you can use the short-cut **shift + Cmd + [a number]** to set a bookmarks.
Unfortunately the following bookmarks are already assigned on all Mac machines:

**shift + Cmd + 3
shift + Cmd + 4**

**Comment by alefragnani** [comment]
Hi @itsthomas ,

The extension was created to mimic **Delphi** bookmarks, which uses these keybindings, and since **Delphi** is exclusive to Windows, it does not conflict with any _native_ shortcut. 

You should change the keybinding to something else. Maybe use `Alt/Option` instead of `Shift`.

I'll update the readme to _alert_ for this issue, so new users would be aware of.

Hope this helps

**Comment by aknuds1** [comment]
I experienced the same problem.

@alefragnani Do you suggest changing the default keybindings of this extension on OS X? If so I might try to make a PR.

**Comment by alefragnani** [comment]
Hi @aknuds1 ,

No, the suggestion was the _user_ to change its keybindings (`File / Preferences / Keyboard Shortcuts`), not the extension itself. To avoid future conflicts in this, or any other of my extensions, I’ve decided to not use keybindings anymore.

What I’m going to do is to update the extension’s README to _alert_ about this conflicts in MacOS.

Hope this helps

**Comment by aknuds1** [comment]
Alright, thanks for the clarification. Happy holidays!
