### ISSUE TITLE
Where is the document that actually tells you what keys will toggle a bookmark?

### ISSUE THREAD

**Issue by rickmas** [alefragnani/vscode-numbered-bookmarks#52]
First time user and new to VS Code and frustrated that the install page doesn't give the most basic information needed, how to toggle a bookmark.

The install page says "You can easily Mark/Unmark bookmarks on any line.". Great, but it doesn't actually tell you HOW to do it.  Where is Ctrl+Shift+<number> mentioned?

**Comment by alefragnani** [comment]
Hi @rickmas ,

I'm sorry to hear that, and I agree the readme could be improved, but most of the information is there, _somehow_ 😁 

### How to toggle a bookmark?
 The commands are listed in 
https://github.com/alefragnani/vscode-numbered-bookmarks#available-commands, and since this extension says _In Delphi style_, I suppose the users would be mostly Delphi users, which already know the keybindings `Ctrl + Shift + 0..9` and `Ctrl + 0..9`

### Where is `Ctrl + Shift + 0..9` mentioned?
 As I said before, if you came from Delphi, you know how to use it, otherwise, I agree, you don't, sorry. But I decided to _not add_ keybindings in my extensions anymore, neither document them, to avoid issues with different keyboard layouts and OSs. You will see the keybindings mentioned in the Command Palette.

You did say you are new to VS Code, so, I suggest you to take your time to learn a bit more about VS Code itself. VS Code has Command Palette as its _core_. Everything that you need to do, should be available there. After a few attempts, you will see how powerful it is. And I give you a tip about it: when looking for commands from extensions, start typing the extension's name, prior the command itself. There is an _unofficial convention_ for extension's developers to prepend the command name, with the extension's name.

Hope this helps

**Comment by rickmas** [comment]
Thanks for the information. I agree you can't get into managing all the different keybindings.  I didn't know what Delphi style was so didn't know that's where I would find the needed keystrokes.  Maybe just a sentence or two that would help a person know where to go find the keybinding information.  Just trying to help others not go through the same pain.  Anyways, I'm liking your extension - thank you!
