### ISSUE TITLE
Unable to run extension. Cannot find bookmark-core

### ISSUE THREAD

**Issue by berthin** [alefragnani/vscode-numbered-bookmarks#54]
Hi, first of all, thanks for the extension!

I want to modify the extension a little bit to have more than 9 bookmarks since I consider that it might be helpful for my purposes (I dont know if that is possible though), so I proceed to clone the code and try to run it, but I keep getting **cannot find module ../vscode-numbered-bookmarks-core/src/model/bookmark** error messages.

Also, looks like the repos "vscode-numbered-booksmarks-core" (https://github.com/alefragnani/vscode-numbered-bookmarks-core/) and "vscode-whats-new" (https://github.com/alefragnani/vscode-whats-new) do not exist or are moved to private?!

Because this is my first experience with vscode extensions, so I am not sure if I am missing something that I had to run or dependencies to install, thus I proceed with the following:

```
$ git clone https://github.com/alefragnani/vscode-numbered-bookmarks.git
$ cd vscode-numbered-bookmarks
$ npm install
$ npm run watch
```

**Comment by alefragnani** [comment]
Hi @berthin ,

The submodules are _private_ for now, because I'm refactoring how the extension works, and also _merging_ some pieces with my other [Bookmarks](http://github.com/alefragnani/vscode-bookmarks) extension. So, for now, you won't be able to manually build it, sorry.

> Because this is my first experience with vscode extensions, so I am not sure if I am missing something that I had to run or dependencies to install, thus I proceed with the following:

Because it is using `git submodules` you should run:

```
   $ git clone https://github.com/alefragnani/vscode-numbered-bookmarks.git
   $ cd vscode-numbered-bookmarks
   $ git submodule init
   $ git submodule update
   $ npm install
   $ code .
   > Tasks: Run Build Task
   > Debug: Start Debugging
```

I'm not sure if you will be able to use something like `Ctrl + 10`, without affecting `Ctrl + 1`. Maybe you will have to use _chords_ (I think that is the term it uses) like the bunch of `Ctrl + K+ ??? ` commands that already existis. You would end up with `Ctrl + 1 + 0`, but `Ctrl + 1` would be dead. 

I suggest you to play with shortcuts in VS Code itself, to see if what it allows you to do, is enought.

Hope this helps

**Comment by alefragnani** [comment]
Hi @berthin ,

The submodules are _private_ for now, because I'm refactoring how the extension works, and also _merging_ some pieces with my other [Bookmarks](http://github.com/alefragnani/vscode-bookmarks) extension. So, for now, you won't be able to manually build it, sorry.

> Because this is my first experience with vscode extensions, so I am not sure if I am missing something that I had to run or dependencies to install, thus I proceed with the following:

Because it is using `git submodules` you should run:

```
   $ git clone https://github.com/alefragnani/vscode-numbered-bookmarks.git
   $ cd vscode-numbered-bookmarks
   $ git submodule init
   $ git submodule update
   $ npm install
   $ code .
   > Tasks: Run Build Task
   > Debug: Start Debugging
```

I'm not sure if you will be able to use something like `Ctrl + 10`, without affecting `Ctrl + 1`. Maybe you will have to use _chords_ (I think that is the term it uses) like the bunch of `Ctrl + K+ ??? ` commands that already existis. You would end up with `Ctrl + 1 + 0`, but `Ctrl + 1` would be dead. 

I suggest you to play with shortcuts in VS Code itself, to see if what it allows you to do, is enought.

Hope this helps
