### ISSUE TITLE
vscode under linux: cannot move to bookmark in other file

### ISSUE THREAD

**Issue by icegood** [alefragnani/vscode-numbered-bookmarks#78]
Use case:
1) Toggle bookmark in some file.
2) Switch to anotrher file
3) Try to jump to bookmark in punt 1)

Expected result: jumping with file switch is OK
Actual result:  text:
The Bookmark 0 is not defined

**Comment by alefragnani** [comment]
Hi @icegood ,

That's the _default behaviour_, because the original extension's idea was to mimic how Delphi works.

But, per user request (#6), it is possible to choose how the bookmarks _navigate through all files_. 

Just change the `numberedBookmarks.navigateThroughAllFiles` setting, that better fit your needs:

Value | Explanation
-- | --
false | default - same behavior as today
replace | you can't have the same numbered bookmark in different files
allowDuplicates | you can have the same numbered bookmark in different files, and if you jump repeatedly to the same number, it will look on other files

Other settings are described in the [README](https://github.com/alefragnani/vscode-numbered-bookmarks/blob/master/README.md)

Hope this helps
