### ISSUE TITLE
Upload to OpenVSX

### ISSUE THREAD

**Issue by ItsDrike** [alefragnani/vscode-numbered-bookmarks#82]
Arch Linux (Linux based operating system distribution) has decided to switch the marketplace for extensions from the [MS Visual Studio Marketplace](https://marketplace.visualstudio.com) to [OpenVSX](https://open-vsx.org/) in [this commit](https://git.archlinux.org/svntogit/community.git/commit/trunk?id=b62a02ec645f16528c0269faf12e362a55efda75).

[Here](https://www.gitpod.io/blog/open-vsx/) are some more details about OpenVSX, its goal, and why it was created

For that reason, I can't use your extension anymore, could you publish on OpenVSX too?
(It's typically just a matter of running `npx ovsx publish` you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))

**Comment by alefragnani** [comment]
Hi @ItsDrike ,

Thank you for your suggestion, but for now, instead of publishing on another store, I’ve decided to publish my extensions using GitHub Releases (in this case https://github.com/alefragnani/vscode-numbered-bookmarks/releases). 

You can download the `.vsix` file and install it manually. It has no difference from the one you find on the MS Marketplace.

Hope this helps.
