### ISSUE TITLE
[QUESTION] - Changing Default Shortcut?

### ISSUE THREAD

**Issue by romansf20** [alefragnani/vscode-numbered-bookmarks#91]
The documentation implies that there is a way to change the default shortcut, but I did not see it anywhere in the configuration/settings. Would be great to just be able to flip between CMD/CTRL

**Comment by alefragnani** [comment]
Hi @romansf20 ,

The shortcut customisation is not something specific to the extension, but a feature from VS Code itself. That's why I just remember the possibility, instead of describing how to do it. 

For more information about it, you can use the VS Code official documentation, more specifically https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor.

Unfortunately, there is no way to change/define shortcuts dynamically (like a setting to choose between `Cmd` instead of `Ctrl` or vice-versa). All shortcuts an extension decides to use, must be _pre-defined_ on its source.

Hope this helps
