### ISSUE TITLE
[BUG] - Do not work on Linux

### ISSUE THREAD

**Issue by Sneirox** [alefragnani/vscode-numbered-bookmarks#93]
**Environment/version**

- Extension version: v7.3.0
- VSCode version: 1.53.0
- OS version: MX Linux 19.3

**Steps to reproduce**

1. Do not mark by pressing:
Cmd + Shift + 1 (2,3,4.....)
Cmd + Ctrl + 1 (2,3,4.....)
Shift + 1 (2,3,4.....)
Ctrl + 1 (2,3,4.....)

**Comment by alefragnani** [comment]
Hi @Sneirox ,

Does it work if you use the commands via **Command Palette**?

If yes, then you probably have a _keyboard shortcut conflict_ (another command already uses it). You can validate using the Keyboard shortcut preferences panel.

Just be aware that on Linux, you should use `Ctrl` instead of `Cmd`.

Hope this helps

**Comment by Sneirox** [comment]
Sorry. It's working. I pressed numpad numbers instead of usuall numbers. Great extension.08.02.2021, 17:38, "Alessandro Fragnani" <notifications@github.com>:
Hi @Sneirox ,
Does it work if you use the commands via Command Palette?
If yes, then you probably have a keyboard shortcut conflict (another command already uses it). You can validate using the Keyboard shortcut preferences panel.
Just be aware that on Linux, you should use Ctrl instead of Cmd.
Hope this helps

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- С уважением, Таланов Александр

**Comment by alefragnani** [comment]
That's great to hear!

Enjoy...
